import Link from "next/link";
import { IconChevron, IconLock, IconRoadmap } from "../lib/icons";

export const metadata = {
  title: "Roadmap · BridgeFlow Operator",
  description:
    "V3 Call Center · V4 Agency · V5 Platform. The vision behind BridgeFlow Operator, beyond what's already shipped.",
};

type Phase = {
  anchor: string;
  version: string;
  title: string;
  badge: string;
  color: string;
  eta: string;
  blurb: string;
  bullets: string[];
};

const PHASES: Phase[] = [
  {
    anchor: "v3",
    version: "V3",
    title: "Call Center",
    badge: "COMING",
    color: "#a78bfa",
    eta: "Next 3 months",
    blurb:
      "Inbound + outbound voice agents. Every call ends, the recording flows straight into the 5-agent pipeline you already use, and the lead is qualified before the rep hangs up the phone.",
    bullets: [
      "VAPI / Twilio webhook → auto-pipeline on call end",
      "Inbound voice agents that book calls without a human",
      "Outbound dialing with persona + objection handling",
      "Real-time agent whisper to the rep mid-conversation",
      "CRM connectors live: HubSpot, Follow Up Boss, Salesforce",
      "Slack approvals as a peer to Telegram",
    ],
  },
  {
    anchor: "v4",
    version: "V4",
    title: "Agency",
    badge: "6MO",
    color: "#f59e0b",
    eta: "6 months out",
    blurb:
      "Per-department autonomous agents — Sales, Support, Legal, Finance — each with their own MCP-secured credential vault. The 5/95 ratio: one human running ninety-five agents.",
    bullets: [
      "Per-department Opus 4.7 agents with role-specific tooling",
      "MCP-secured credential vault — no plaintext envs",
      "Cross-agent handoffs (Sales → Onboarding → CSM)",
      "Weekly P&L report generated by the agency itself",
      "Full observability — every decision audit-trailed",
      "5/95 human-to-agent ratio without losing the human signal",
    ],
  },
  {
    anchor: "v5",
    version: "V5",
    title: "Platform",
    badge: "$1M",
    color: "#eab308",
    eta: "$1M ARR target",
    blurb:
      "Multi-tenant platform with isolated workspaces and white-label option. Every operator runs their own BridgeFlow instance — same five-agent core, their domain, their identity, their CRM.",
    bullets: [
      "Multi-tenant workspaces with strict data isolation",
      "White-label deployment for agencies + consultancies",
      "Usage-based billing (calls processed × tier)",
      "Department agents with full MCP tooling per tenant",
      "SSO + role-based access for ops teams",
      "Public marketplace for agent personas + workflow templates",
    ],
  },
];

export default function RoadmapPage() {
  return (
    <div className="space-y-8 max-w-4xl">
      <header>
        <div className="inline-flex items-center gap-2 rounded-full border border-accent/35 bg-accent/[0.07] px-3 py-1.5 text-[11px] font-mono uppercase tracking-wider text-accent mb-4">
          <span className="w-1.5 h-1.5 rounded-full bg-accent shadow-glow-accent animate-blink" />
          Architect from V5 · build from V1
        </div>
        <h1 className="text-3xl font-semibold tracking-tight text-ink flex items-center gap-2">
          <IconRoadmap className="w-7 h-7 text-accent" />
          Roadmap
        </h1>
        <p className="text-sm text-muted mt-2 max-w-2xl leading-relaxed">
          What's already shipped lives at <Link href="/dashboard" className="text-accent hover:underline">/dashboard</Link>. Below is the
          forward shape — the platform we designed from before we built V1, then
          stripped to its first stage. Every locked surface in the app links here.
        </p>
      </header>

      <div className="space-y-5">
        {PHASES.map((p) => (
          <section
            key={p.anchor}
            id={p.anchor}
            className="scroll-mt-20 rounded-xl border bg-surface shadow-inset-hair p-6 space-y-4"
            style={{
              borderColor: `${p.color}40`,
              boxShadow: `0 0 0 1px ${p.color}10 inset`,
            }}
          >
            <div className="flex items-center justify-between gap-3 flex-wrap">
              <div className="flex items-center gap-3 min-w-0">
                <div
                  className="w-10 h-10 rounded-lg flex items-center justify-center border shrink-0"
                  style={{
                    color: p.color,
                    borderColor: `${p.color}55`,
                    background: `${p.color}12`,
                    boxShadow: `0 0 18px ${p.color}30`,
                  }}
                >
                  <IconLock className="w-4 h-4" />
                </div>
                <div className="min-w-0">
                  <div
                    className="text-[10px] font-mono uppercase tracking-wider"
                    style={{ color: p.color }}
                  >
                    {p.version} · {p.eta}
                  </div>
                  <h2 className="text-xl font-semibold text-ink leading-tight">
                    {p.title}
                  </h2>
                </div>
              </div>
              <span
                className="text-[10px] font-mono uppercase tracking-wider px-2 py-1 rounded border"
                style={{
                  color: p.color,
                  borderColor: `${p.color}55`,
                  background: `${p.color}12`,
                }}
              >
                {p.badge}
              </span>
            </div>

            <p className="text-[14px] text-ink-muted leading-relaxed max-w-3xl">
              {p.blurb}
            </p>

            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-1.5 text-[12px] text-muted leading-relaxed">
              {p.bullets.map((b) => (
                <li key={b} className="flex items-start gap-2">
                  <span
                    className="mt-1.5 w-1 h-1 rounded-full shrink-0"
                    style={{ backgroundColor: p.color }}
                  />
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>

      <footer className="rounded-xl border border-border bg-bg/40 p-5 flex items-center justify-between gap-3 flex-wrap">
        <div>
          <div className="text-sm font-semibold text-ink">
            What's live today
          </div>
          <div className="text-[12px] text-muted mt-0.5">
            5-agent pipeline · Telegram approvals · HubSpot sync · n8n workflow
            generator · in-dashboard AI consultant.
          </div>
        </div>
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-1.5 text-[12px] font-semibold px-3 py-2 rounded-md bg-accent text-bg hover:bg-accent/90 cursor-pointer shadow-glow-accent"
        >
          Open the operator
          <IconChevron className="w-3.5 h-3.5" />
        </Link>
      </footer>
    </div>
  );
}
